dist: xenial
language: minimal

before_install:
  - sudo apt-get -y update
  - sudo apt-get -y install zip make wget python
  - sudo apt-get -y install python-pip
  - sudo pip install awscli
  - sudo k8s/eksctl.sh

install:
  - echo | ssh-keygen -P ''
  - make create
  - make delete